### ISSUE TITLE
FileProvider implementation for Android

### ISSUE THREAD

**Issue by thompson7799** [chuangbo/react-native-multi-share#2]
Im currently getting the following error on android. 
'exposed beyond app through clipdata.item.geturi() android'

Android sdk 24+ requires any files from an external source be provided through FileProvider. Hence any local images starting with 'file;//' no longer work.
Decrementing the targetSdkVersion is not a suitable workaround as it will be enforced by Google in August.

Would it be possible to add support for sdk 24+ by doing a FileProvider implementation.

**Comment by chuangbo** [comment]
Thanks for the notice.

I have a question because I'm not familiar with Android development. React-Native itself still using sdk 23, so it should follow the Google's August policy too, right?

**Comment by chuangbo** [comment]
Thanks @SharpMobileCode
